"""Common."""
from __future__ import annotations

SALT_SENSOR = {
    "createdDate": 1664059201347,
    "userType": "EU",
    "deviceType": "SSS1",
    "addressId": "address1",
    "status": "ACTIVE",
    "pname": "Salt Level Sensor",
    "order": 1,
    "email": "**REDACTED**",
    "homeFlag": True,
    "deviceId": "**REDACTED**",
    "parentGroup": "Home",
    "userId": "**REDACTED**",
    "productInfo": {
        "maker": "Pentair",
        "survey": {
            "water_products_you_own": [
                "Whole Home Filter",
                "Reverse Osmosis System",
                "Refrigerator Filter",
            ],
            "water_softener_brand": "Other",
            "water_softener_type": "Side-by-Side",
        },
        "model": "SSS",
        "visible": True,
        "nickName": "Salt Level Sensor",
        "order": 1,
    },
    "arn": "**REDACTED**",
    "parentGroupWithoutMlt": "Home",
    "jobId": "",
    "jobStatus": "",
    "currentFWVersion": "1.0.2",
    "latestFWVersion": "",
    "isRm": False,
    "online": False,
    "fields": {
        "salt_level": "3",
        "average_salt_usage_per_day": "3.51",
        "low_battery_alert": "0",
        "sensor_fault": "0",
        "calibration_status_alert": "0",
        "salt_level_alert": "3",
        "battery_level": "0",
    },
    "lastReport": 1688970159228,
    "deb_off_stat": False,
    "deb_off_time": 1688970166106,
}
